import Search from "@/components/Search";

// export const metadata = {
//   title: "Home page",
//   description: "Generated by create next app",
// };

export default async function SearchPage() {
  return (
    <div className="pb-[3000px]">
      <Search />
    </div>
  );
}
