// export const metadata = {
//   title: "Home page",
//   description: "Generated by create next app",
// };

import Form from "@/components/Form";

export default async function Contact({ params }) {
  return (
    //     // <div className="container">
    //       {/*
    // 6e41f45f-095a-4428-a182-5bd54e9a2c37
    // */}

    <div className="relative my-28 container">
      <div className="item container mx-auto max-w-7xl">
        <div className="mb-20 md:mb-0 w-full md:px-12 md:w-7/12 md:float-left">
          <Form />
        </div>
        <div className="w-full sm:w-8/12 mx-auto md:px-12 md:w-5/12 md:float-left">
          <div className="mb-10 max-w-md mx-auto sm:float-left sm:w-1/2 md:mt-10 md:w-full lg:mt-0">
            <h4 className="text-blue font-bold font-inter text-lg w-10/12 mx-auto sm:mx-0 md:mx-auto mb-3">
              Contactgegevens
            </h4>
            <ul className="text-gray w-10/12 mx-auto sm:mx-0 md:mx-auto">
              <li className="mb-2 text-darkblue">06 43 79 15 84</li>
              <li className="mb-2 text-darkblue">service@gedenk-sieraad.nl</li>
              <li className="mb-2 text-darkblue">www.gedenk-sieraad.nl</li>
            </ul>
          </div>
          <div className="max-w-md mx-auto sm:float-left sm:w-1/2 md:w-full">
            <h4 className="text-blue font-bold font-inter text-lg w-10/12 mx-auto sm:mx-0 md:mx-auto mb-3">
              Locatie
            </h4>
            <ul className="text-gray w-10/12 mx-auto sm:mx-0 md:mx-auto">
              <li className="mb-2 text-darkblue">Straatsburglaan 10</li>
              <li className="mb-2 text-darkblue">6137 JC Sittard-Geleen</li>
            </ul>
          </div>
          <div className="clear-both"></div>
        </div>
        <div className="clear-both"></div>
      </div>
      {/* </div> */}
    </div>
  );
}
