"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { ShopifyProvider, CartProvider } from "@shopify/hydrogen-react";

import Navbar from "./components/Navbar.1";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const storeDomain = process.env.NEXT_PUBLIC_STORE_DOMAIN;
// const storefrontApiToken = process.env.NEXT_PUBLIC_STOREFRONT_API_TOKEN;

// console.log("Store Domain:", storeDomain);
// console.log("Storefront API Token:", storefrontApiToken);

export default function RootLayout({ children }) {
  console.log(process.env.NEXT_PUBLIC_STORE_DOMAIN);
  return (
    <html lang="nl">
      <body className={inter.className}>
        <ShopifyProvider
          storeDomain={`https://${process.env.NEXT_PUBLIC_STORE_DOMAIN}`}
          storefrontToken={process.env.NEXT_PUBLIC_STOREFRONT_API_TOKEN}
          storefrontApiVersion="2023-10"
          countryIsoCode="NL"
          languageIsoCode="NL"
        >
          <CartProvider
            onLineAdd={() => {
              console.log("a line is being added");
            }}
            onLineAddComplete={() => {
              console.log("a line has been added");
            }}
          >
            <Navbar />
            {children}
          </CartProvider>
        </ShopifyProvider>

        {/* ToDo Footer */}
      </body>
    </html>
  );
}
