import Link from "next/link";
import Hero from "@/components/Hero";

export const metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default async function Home() {
  return (
    <div className="pb-[3000px] ">
      <Hero />
    </div>
  );
}
